### ISSUE TITLE
analiza odgovora - u izradi

### ISSUE THREAD

**Issue by hrenci96** [DevpoolTeam/Devpool#3]
odrada potrebna, nece biti gotovo do 06.06.

**Comment by JKuhar** [comment]
<?php
  // including FusionCharts PHP wrapper
  include("/fusioncharts.php"); 

$dbc = mysqli_connect('localhost', 'root', '' , 'survey_db') or die('Error connecting to the MySQL Server');
$query = "SELECT DISTINCT * FROM questions ";

$result = mysqli_query($dbc, $query) or die ("Error tebra");
 

 

/*
$strQuery = "SELECT DISTINCT * FROM questions; ";
 
$result = $dbhandle->query($strQuery) or exit("Error code ({$dbhandle->errno}): {$dbhandle->error}");

*/
if ($result) {
 
  // creating an associative array to store the chart attributes        
  $arrData = array(
    "chart" => array(
      "theme" => "fint",
      "caption" => "Browser Market Share",
      "subcaption" => "February 2016",
      "captionFontSize" => "24",
      "paletteColors" => "#A2A5FC, #41CBE3, #EEDA54, #BB423F #,F35685",
      "baseFont" => "Quicksand, sans-serif",
      //more chart configuration options
    )
  );
 
  $arrData["data"] = array();
 
  // iterating over each data and pushing it into $arrData array
  while ($row = mysqli_fetch_array($result)) {
    array_push($arrData["data"], array(
      "label" => $row["browser"],
      "value" => $row["shareval"]
    ));
  }
 
  $jsonEncodedData = json_encode($arrData);
 
}

// creating FusionCharts instance
$doughnutChart = new FusionCharts("doughnut2d", "browserShareChart" , "100%", "450", "doughnut-chart", "json", $jsonEncodedData);
     
// FusionCharts render method
$doughnutChart->render();
     
// closing database connection      
mysqli_close($dbc); 



?>

<script>

var myData=[<?php 
while($info=mysqli_fetch_array($query))
    echo $info['prvopitanje_prviodgovor'].','.$info['prvopitanje_drugiodgovor'].','.$info['prvopitanje_treciodgovor'].','.$info['drugopitanje_prviodgovor'].','.$info['drugopitanje_drugiodgovor'].','.$info['drugipitanje_treciodgovor'].','.$info['trecepitanje_odgovor']; /* We use the concatenation operator '.' to add comma delimiters after each data value. */
?>];

<?php
$data=mysqli_query($mysqli,"SELECT * FROM t_test");
?>

var myLabels=[<?php 
while($info=mysqli_fetch_array($data))
    echo '"'.$info['prvopitanje'].','.$info['drugopitanje'].','.$info['trecepitanje']; /* The concatenation operator '.' is used here to create string values from our database names. */
?>];

</script>

<script>

	window.onload=function(){
	zingchart.render({
    id:"myChart",
    width:"100%",
    height:400,
    data:{
    "type":"bar",
    "title":{
        "text":"Data Pulled from MySQL Database"
    },
    "scale-x":{
        "labels":myLabels
    },
    "series":[
        {
            "values":myData
        }
]
}
});
};	

</script>

<html>
 
<head>
  
  <script type="text/javascript" src="/path/to/fusioncharts.js"></script>
  <script type="text/javascript" src="/path/to/fusioncharts.charts.js"></script>
</head>

<body>
	<div id="doughnut-chart">A beautiful donut chart is on its way!</div>
</body>
 
</html>

**Comment by hrenci96** [comment]
protip: click on edit pen to see whole code in upper comment
